### ISSUE TITLE
How can i install it in npm?

### ISSUE THREAD

**Issue by coolguy001tv** [Aufree/nwjs-updater#2]
It's great u've solved some problem in node-webkit-updater. But how can i install your nwjs-updater from npm. At first, I thought it's `npm i nwjs-updater` but I failed.

**Comment by Aufree** [comment]
Sorry, I didn't upload this package to npm server, but you can fork this package, and do whatever you want.

**Comment by coolguy001tv** [comment]
However, thank you for the solution, I just cloned it in my project, and it works.
You may close the PR if you like.
